#pragma once

#define START 1
#define INSIDE_ELEMENT 2
#define PROCESS_ELEMENT 3
#define PROCESS_ATTRIBUTE 4
#define INSIDE_COMMENT 5
#define INSIDE_TAG 6
#define INSIDE_SPECIAL_TAG 7
#define DROP_ATTRIBUTE_VALUE 8
#define NEXT_ATTRIBUTE 9
#define END_ELEMENT 10
#define DROP_SPECIAL_TAG 11
#define DROP_ATTRIBUTE_VALUE_ESCAPED 12